# Build the project using Dune
build:
	dune build

# Run the executable using Dune exec
run:
	dune exec ./main.exe

# Clean up the build artifacts using Dune
clean:
	dune clean

# Phony targets to avoid conflicts with filenames
.PHONY: build run clean

